apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/waiyanwh/sample-nodejs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true