name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # First approach  
      - name: Import Creds
        uses: mcmarkj/1password-actions@v2
        id: creds
        with:
          connect-server-url: https://connect.staging-internal.opn.dev
          connect-server-token: ${{ secrets.CONNECT_SERVER_TOKEN }}
          export-env-vars: "true"
          secret-path: |
            Github Action Vault > Test Project > username | USERNAME
            Github Action Vault > Test Project > password | PASSWORD

      - run: echo "$USERNAME"

      - run: echo "$PASSWORD"

      # -----------------------------------------------------------------------------
      # Second Approach
      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          connect-host: https://connect.staging-internal.opn.dev
          connect-token: ${{ secrets.CONNECT_SERVER_TOKEN }}

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        env:
          USERNAME: op://github-action-vault/test-project/username
          PASSWORD: op://github-action-vault/test-project/password

      - run: echo "$USERNAME"

      - run: echo "$PASSWORD"