name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: waiyanwinhtain/sample-nodejs:latest
          build-args: |
            TOKEN=Test
            
      - name: Import Creds
        uses: mcmarkj/1password-actions@v2
        id: creds
        with:
          connect-server-url: https://connect.staging-internal.opn.dev
          connect-server-token: ${{ secrets.CONNECT_SERVER_TOKEN }}
          export-env-vars: "true"
          secret-path: |
            Github Action Vault > Test Project > username | USERNAME
            Github Action Vault > Test Project > password | PASSWORD