name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: waiyanwinhtain/sample-nodejs:latest
  
  kubectl:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
    # needs: docker
    steps:
      - name: apply argocd app
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: get pods
        run: kubectl get pods